version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "07:00"
  open-pull-requests-limit: 20
