[package]
name = "rust-toolchain-manifest"
version = "0.1.0"
edition = "2021"
description = "Query the official rust release manifests"
authors = [ "Alexander Kenji Berthold" ]
license = "MIT"
include = ["src/main.rs", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.1", features = ["derive"] }
reqwest = { version = "0.11.14", features = ["blocking"] }
semver = { version = "1.0.16", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.145"
serde_json = {version = "1.0.91", features = ["preserve_order"]}
thiserror = "1.0.38"
toml = "0.7.1"
