name: "actionlint"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  actionlint:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v15
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "actionlint"
      run: nix develop .#actionlintShell --command actionlint --ignore 'SC2002'
