# Workflow, consisting of jobs that only need to be run,
# once `*nix`, or `flake.lock`, or `rust-toolchain.toml` files change
name: "nix develop"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
    paths:
      - '**.nix'
      - 'flake.lock'
      - 'flake.nix'
      - 'rust-toolchain.toml'
  push:
    branches: [ main ]
    paths:
      - '**.nix'
      - 'flake.lock'
      - 'flake.nix'
      - 'rust-toolchain.toml'

jobs:
  develop:
    runs-on: ubuntu-latest
    environment: cachix
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: 'nix develop --command "echo hello"'
      run: nix develop
    - name: "ldd version"
      run: nix develop --command ldd --version

  treefmt:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "treefmt"
      run: nix develop .#fmtShell --command treefmt --fail-on-change
