name: "nix"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  dependencies:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "build dependencies"
      run: nix build -Lvv --no-update-lock-file --show-trace .#cargoArtifacts

  build:
    needs: dependencies
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "nix build"
      run: nix build -Lvv --no-update-lock-file --show-trace

  doc:
    needs: dependencies
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "documentation"
      run: nix build -Lvv --no-update-lock-file --show-trace .#cargoDoc

  clippy:
    needs: dependencies
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "clippy"
      run: nix build -Lvv --no-update-lock-file --show-trace .#cargoClippy

  deny:
    needs: dependencies
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "deny"
      run: nix build -Lvv --no-update-lock-file --show-trace .#cargoDeny

  check:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v13
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "nix flake check"
      run: nix flake check -Lvv --no-update-lock-file --show-trace
