name: "nix"

on:
  workflow_dispatch: # allows manual triggering
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v12
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "nix build"
      run: nix build -Lvv --no-update-lock-file --show-trace

  clippy:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v12
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "cargo clippy"
      run: nix develop --command cargo clippy

  cargo-deny:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v12
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "cargo deny"
      run: nix develop --command cargo deny check licenses sources
  check:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
      with:
        diagnostic-endpoint: ""
    - uses: cachix/cachix-action@v12
      with:
        name: kenji
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "nix flake check"
      run: nix flake check -Lvv --no-update-lock-file --show-trace
